package com.dafukeji.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dafukeji.daogenerator.Point;
import com.dafukeji.daogenerator.Cure;

import com.dafukeji.daogenerator.PointDao;
import com.dafukeji.daogenerator.CureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pointDaoConfig;
    private final DaoConfig cureDaoConfig;

    private final PointDao pointDao;
    private final CureDao cureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pointDaoConfig = daoConfigMap.get(PointDao.class).clone();
        pointDaoConfig.initIdentityScope(type);

        cureDaoConfig = daoConfigMap.get(CureDao.class).clone();
        cureDaoConfig.initIdentityScope(type);

        pointDao = new PointDao(pointDaoConfig, this);
        cureDao = new CureDao(cureDaoConfig, this);

        registerDao(Point.class, pointDao);
        registerDao(Cure.class, cureDao);
    }
    
    public void clear() {
        pointDaoConfig.getIdentityScope().clear();
        cureDaoConfig.getIdentityScope().clear();
    }

    public PointDao getPointDao() {
        return pointDao;
    }

    public CureDao getCureDao() {
        return cureDao;
    }

}
